In [112]:
import numpy as np

**Testing**

In [113]:
a = np.array([[1,2,3],[4,5,6]])
display(type(a), a.shape, a, a[0][1], a[0], a[0][0], a[1], a[1][1])

numpy.ndarray

(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

2

array([1, 2, 3])

1

array([4, 5, 6])

5

In [114]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [115]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [116]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [117]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [118]:
np.random.random((3,5))

array([[0.06936843, 0.5005678 , 0.60458999, 0.86914102, 0.03155273],
       [0.12028125, 0.66155649, 0.08344119, 0.45006431, 0.65383391],
       [0.19754686, 0.67792339, 0.88189631, 0.57899721, 0.13419156]])

In [119]:
np.random.randint(1,100,(4,3))

array([[49,  5, 13],
       [ 5, 12, 41],
       [33, 69, 37],
       [34, 91,  1]])

**Slicing**

In [120]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
b = a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [122]:
a[0,1]

2

In [123]:
b[0,0]

2

In [124]:
b[0,0] = 77
b[0,0]

77

In [125]:
a[0,1]

77

In [126]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [127]:
a[1,:]

array([5, 6, 7, 8])

In [128]:
a[[1],:]

array([[5, 6, 7, 8]])

In [129]:
a[:,[1]]

array([[77],
       [ 6],
       [10]])

In [130]:
a[:,1]

array([77,  6, 10])

**Selection and Mutation**

In [131]:
a = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [132]:
b = np.array([0,2,0,1])
b

array([0, 2, 0, 1])

In [133]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [134]:
a[np.arange(4), b] += 10
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

**Broadcasting**

In [135]:
x = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

In [136]:
y = np.empty_like(x)

In [137]:
display(x[1, :])
display(x[2, :])
display(x[3, :])

array([4, 5, 6])

array([7, 8, 9])

array([10, 11, 12])

In [138]:
for i in range(4):
    y[i, :] = x[i, :] + v

y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [139]:
vv = np.tile(x,(4,1))
vv

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [140]:
vv = np.tile(v,(4,1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [141]:
x + vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [142]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [143]:
v = np.array([1,2,3])
display(v)
w = np.array([4,5])
w

array([1, 2, 3])

array([4, 5])

In [144]:
np.reshape(v, (3,1))*w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [148]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [146]:
x+v

array([[2, 4, 6],
       [5, 7, 9]])

In [147]:
((x.T + w).T)

array([[ 5,  6,  7],
       [ 9, 10, 11]])