In [21]:
import numpy  as np

In [22]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

### Forward Propogation

In [23]:
Wnode1 = np.array([0.5, 1.5, 0.8])
Wnode2 = np.array([0.8, 0.2, -1.6])
ipnode = np.array([1, 0.7, 1.2])

In [43]:
rn1 = sigmoid(np.dot(Wnode1, ipnode))
rn2 = sigmoid(np.dot(Wnode2, ipnode))
nip = np.array([1, rn1, rn2])
nip

array([1.        , 0.92483989, 0.27289178])

In [25]:
Won1 = np.array([0.9, -1.7, 1.6])
Won2 = np.array([1.2, 2.1, -0.2])

In [26]:
op1 = sigmoid(np.dot(nip, Won1))
op2 = sigmoid(np.dot(nip, Won2))
ans = np.array([op1, op2])
ans

array([0.44137071, 0.95637774])

### Error

In [27]:
error = [1,0] - ans
error

array([ 0.55862929, -0.95637774])

In [30]:
op = np.array([1,0])

### Back Propogation

In [28]:
def errorcalc(p, a):
    return (p-a)*p*(1-p)

In [47]:
errorcalc(ans[0], op[0])*nip[1], errorcalc(ans[1], op[1])*nip[1]

(-0.12738475900610174, 0.03690061677035571)