In [69]:
import numpy as np

In [70]:
X = [
        np.array([0,0]),
        np.array([0,1]),
        np.array([1,0]),
        np.array([1,1])
    ]
NX = [
        np.array([0]),
        np.array([1])
    ]
X

[array([0, 0]), array([0, 1]), array([1, 0]), array([1, 1])]

In [71]:
def step_fn(x):
    return 0 if x < 0 else 1

In [72]:
Abias ,Aweights = -1.5, np.array([1,1])
Obias ,Oweights = -0.5, np.array([1,1])
Nbias ,Nweights = np.array([0.5]), -1

In [73]:
def AND_OR(weights, bias, X):
    res = np.array([])
    for i in X:
        u = np.dot(i,weights)+bias
        res = np.append(step_fn(u),res)
    return res

In [74]:
def NOT(weights, bias, X):
    res = np.array([])
    for i in X:
        u = np.dot(i,weights)+bias
        res = np.append(step_fn(u),res)
    return res

In [75]:
ans = AND_OR(Aweights, Abias, X)
ans = AND_OR(Oweights, Obias, X)
ans = NOT(Nweights, Nbias, NX)
ans

array([0., 1.])

In [76]:
SA = AND_OR(Aweights, Abias, X)
SO = AND_OR(Oweights, Obias, X)

SN = NOT(Nweights, Nbias, SA)

X = np.vstack((SN, SO)).T

# OP = AND_OR(Aweights, Abias, X[0])

# ips = np.array([])
# for i in X:
#     ips = np.append(ips,np.array([i])
# ips
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [97]:
X[0][1]

1.0

In [91]:
# ip1 = np.array([])
# ip2 = np.array([])
# for i in X:
#     ip1 = np.concatenate((ip1, np.array( [i[0]] )))
#     ip2 = np.concatenate((ip2, np.array( [i[1]] )))
# ip1, ip2
# fip = np.stack((ip1, ip2), axis=1)
# fip

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [99]:
OX = [
        np.array([X[0][0],X[0][1]]),
        np.array([X[1][0],X[1][1]]),
        np.array([X[2][0],X[2][1]]),
        np.array([X[3][0],X[3][1]])
    ]
OX

[array([1., 1.]), array([1., 1.]), array([1., 1.]), array([0., 0.])]

In [100]:
OP = AND_OR(Aweights, Abias, OX)
OP

array([0., 1., 1., 1.])